# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/afreixas/Documents/cpp_native_test/HelloStaticLib

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/afreixas/Documents/cpp_native_test/HelloStaticLib

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/afreixas/Documents/cpp_native_test/HelloStaticLib/CMakeFiles /home/afreixas/Documents/cpp_native_test/HelloStaticLib/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/afreixas/Documents/cpp_native_test/HelloStaticLib/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named HelloStaticLib

# Build rule for target.
HelloStaticLib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HelloStaticLib
.PHONY : HelloStaticLib

# fast build rule for target.
HelloStaticLib/fast:
	$(MAKE) -f CMakeFiles/HelloStaticLib.dir/build.make CMakeFiles/HelloStaticLib.dir/build
.PHONY : HelloStaticLib/fast

#=============================================================================
# Target rules for targets named StaticLib

# Build rule for target.
StaticLib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 StaticLib
.PHONY : StaticLib

# fast build rule for target.
StaticLib/fast:
	$(MAKE) -f Libraries/CMakeFiles/StaticLib.dir/build.make Libraries/CMakeFiles/StaticLib.dir/build
.PHONY : StaticLib/fast

helloStaticLib.o: helloStaticLib.cpp.o
.PHONY : helloStaticLib.o

# target to build an object file
helloStaticLib.cpp.o:
	$(MAKE) -f CMakeFiles/HelloStaticLib.dir/build.make CMakeFiles/HelloStaticLib.dir/helloStaticLib.cpp.o
.PHONY : helloStaticLib.cpp.o

helloStaticLib.i: helloStaticLib.cpp.i
.PHONY : helloStaticLib.i

# target to preprocess a source file
helloStaticLib.cpp.i:
	$(MAKE) -f CMakeFiles/HelloStaticLib.dir/build.make CMakeFiles/HelloStaticLib.dir/helloStaticLib.cpp.i
.PHONY : helloStaticLib.cpp.i

helloStaticLib.s: helloStaticLib.cpp.s
.PHONY : helloStaticLib.s

# target to generate assembly for a file
helloStaticLib.cpp.s:
	$(MAKE) -f CMakeFiles/HelloStaticLib.dir/build.make CMakeFiles/HelloStaticLib.dir/helloStaticLib.cpp.s
.PHONY : helloStaticLib.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... HelloStaticLib"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... StaticLib"
	@echo "... helloStaticLib.o"
	@echo "... helloStaticLib.i"
	@echo "... helloStaticLib.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

